# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=300)),
                ('was_published', models.DateTimeField()),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('sterilized', models.BooleanField()),
                ('accustomed', models.BooleanField()),
                ('get_home', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='find_cat/static/find_cat/img/')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_cat.Pet')),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_cat.Sex'),
        ),
        migrations.AddField(
            model_name='pet',
            name='type_animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_cat.Type_of_animal'),
        ),
        migrations.AddField(
            model_name='ad',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_cat.Pet'),
        ),
    ]
